# Enable the Userspace subsystem
CONFIG_USERSPACE=y

# Allow User threads to use the console (printk)
CONFIG_STDOUT_CONSOLE=y

# Grant user threads permission to use the system timer/clock
CONFIG_DYNAMIC_OBJECTS=y
